Controllers/PlayerController.cs
using System.Linq;
using System.Threading.Tasks;
using GGStream.Data;
using GGStream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace GGStream.Controllers
{
    public class PlayerController : Controller
    {
        private readonly IConfiguration _config;
        private readonly Context _context;
        private readonly IApplicationDateTime _dateTime;

        public PlayerController(Context context, IConfiguration config, ApplicationDateTime dateTime)
        {
            _context = context;
            _config = config;
            _dateTime = dateTime;
        }

        [Route("/{url}/{id?}")]
        public async Task<IActionResult> ViewStream(string url, string id)
        {
            if (url == null) return NotFound();

            ViewData["IngestEndpoint"] = $"rtmp://{_config.GetValue<string>("IngestEndpoint")}:1935/app/";

            var collection = await _context.Collection.FindAsync(url);
            if (collection == null)
            {
                // Check if it's a direct stream link
                var stream = await _context.Stream.FindAsync(url);
                if (stream == null) return NotFound();

                if ((stream.StartDate == null || stream.StartDate < _dateTime.Now()) &&
                    (stream.EndDate == null || stream.EndDate > _dateTime.Now()))
                {
                    // Attach Collection to stream
                    var streamCollection = await _context.Collection.FindAsync(stream.CollectionURL);

                    stream.Collection = streamCollection;
                    return View(stream);
                }

                ViewData["Message"] = "This stream isn't live right now.";
                ViewData["Color"] = "info";
                ViewData["Icon"] = "fad fa-calendar-times";

                return View("Error");
            }

            if (id == null)
            {
                // Determine which stream to play
                if (collection.Private) return NotFound();

                var stream = StreamToPlay(collection);
                if (stream != null) return View(stream);

                ViewData["Message"] = "There are no streams live right now.";
                ViewData["Color"] = "info";
                ViewData["Icon"] = "fad fa-calendar-times";

                return View("Error");
            }

            {
                // This is a collection-stream link
                var stream = await _context.Stream.FindAsync(id);
                if (stream == null || stream.CollectionURL != url) return NotFound();

                // Attach Collection to stream
                var streamCollection = await _context.Collection.FindAsync(stream.CollectionURL);

                stream.Collection = streamCollection;
                return View(stream);
            }
        }

        private Stream StreamToPlay(Collection collection)
        {
            var today = _dateTime.Now();
            var stream = _context.Stream.FirstOrDefault(s =>
                s.Private != true &&
                s.Collection.URL == collection.URL &&
                (s.StartDate == null || s.StartDate < today) &&
                (s.EndDate == null || s.EndDate > today));

            if (stream == null) return null;

            // Attach collection to stream
            stream.Collection = collection;

            return stream;
        }
    }
}

Controllers/StreamsController.cs
using System.Linq;
using System.Threading.Tasks;
using GGStream.Data;
using GGStream.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GGStream.Controllers
{
    [Authorize]
    public class StreamsController : Controller
    {
        private readonly Context _context;

        public StreamsController(Context context)
        {
            _context = context;
        }

        [Route("/admin/streams")]
        public async Task<IActionResult> Index()
        {
            ViewData["DisableCreate"] = true;
            return View(await _context.Stream.ToListAsync());
        }

        [Route("/admin/{url}/streams")]
        public async Task<IActionResult> CollectionIndex(string url)
        {
            var collection = await _context.Collection.FindAsync(url);

            if (collection == null) return NotFound();

            var streams = await _context.Stream.Where(s => s.CollectionURL == url).ToListAsync();

            streams.ConvertAll(s =>
            {
                s.Collection = collection;
                return s;
            });

            return View("Index", streams);
        }

        [Route("/admin/{url}/streams/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null) return NotFound();

            var stream = await _context.Stream.FindAsync(id);
            if (stream == null) return NotFound();

            return View(stream);
        }

        [Route("/admin/{url}/streams/create")]
        public async Task<IActionResult> Create(string url)
        {
            var collection = await _context.Collection.FindAsync(url);

            if (collection == null) return NotFound();

            ViewData["Collection:Name"] = collection.Name;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/admin/{url}/streams/create")]
        public async Task<IActionResult> Create(string url, [Bind("Name,StartDate,EndDate,Private")]
            Stream stream)
        {
            var collection = await _context.Collection.FindAsync(url);

            if (collection == null)
            {
                return NotFound();
            }

            stream.Collection = collection;
            stream.CollectionURL = url;
            ViewData["Collection:Name"] = collection.Name;

            if (ModelState.IsValid)
            {
                // ReSharper disable StringLiteralTypo
                stream.ID = await Nanoid.Nanoid.GenerateAsync(
                    "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ", 10);
                stream.StreamKey =
                    $"{url}-{await Nanoid.Nanoid.GenerateAsync("_0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")}";
                // ReSharper restore StringLiteralTypo
                _context.Add(stream);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CollectionIndex), new {url});
            }

            return View(stream);
        }

        [Route("/admin/{url}/streams/{id}/edit")]
        public async Task<IActionResult> Edit(string url, string id)
        {
            if (id == null) return NotFound();

            var stream = await _context.Stream.FindAsync(id);
            if (stream == null || stream.CollectionURL != url) return NotFound();
            return View(stream);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("/admin/{url}/streams/{id}/edit")]
        public async Task<IActionResult> Edit(string url, string id,
            [Bind("ID,CollectionURL,StreamKey,Name,StartDate,EndDate,Private")]
            Stream stream)
        {
            if (id != stream.ID || url != stream.CollectionURL) return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stream);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StreamExists(stream.ID))
                        return NotFound();
                    throw;
                }

                return RedirectToAction(nameof(CollectionIndex), new {url});
            }

            return View(stream);
        }

        [Route("/admin/{url}/streams/{id}/delete")]
        public async Task<IActionResult> Delete(string url, string id)
        {
            if (id == null || url == null) return NotFound();

            var stream = await _context.Stream.FindAsync(id);
            if (stream == null || stream.CollectionURL != url) return NotFound();

            return View(stream);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Route("/admin/{url}/streams/{id}/delete")]
        public async Task<IActionResult> DeleteConfirmed(string url, string id)
        {
            var stream = await _context.Stream.FindAsync(id);
            if (stream == null || stream.CollectionURL != url) return NotFound();

            _context.Stream.Remove(stream);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(CollectionIndex), new {url});
        }

        private bool StreamExists(string id)
        {
            return _context.Stream.Any(e => e.ID == id);
        }
    }
}

Views/Player/ViewStream.cshtml
@using Microsoft.Extensions.Configuration
@model Stream

@{
    ViewData["Title"] = Model.Name + " - " + Model.Collection.Name;
    ViewData["Title:Nav"] = Model.Collection.Name;
    ViewData["Subtitle:Nav"] = Model.Name;
    ViewData["Icon:Nav"] = Model.Collection.Icon;
    ViewData["Color:Nav"] = Model.Collection.DarkColor;
    ViewData["Color:NavBtn"] = Model.Collection.DarkerColor;
    ViewData["Color:Base"] = Model.Collection.BaseColor;
    ViewData["Color:Link"] = Model.Collection.LighterColor;
    ViewData["Color:Accent"] = Model.Collection.LightestColor;
    ViewData["Page:Align"] = "center";
    ViewData["HideLoginUI"] = true;
}

<div id="player"></div>

@section Scripts {
    @inject IConfiguration Configuration

    @await Html.PartialAsync("Partials/_OvenPlayer", new OvenPlayerViewModel(Configuration)
    {
        StreamKey = Model.StreamKey
    })
}

@section Navbar {
    @{
        if (Model.Collection.InstructionType != InstructionType.None)
        {
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-outline-secondary" href="#" data-toggle="modal" data-target="#modal-ins-@Model.Collection.InstructionType">
                    <i class="far fa-gamepad-alt"></i>
                    <span class="nav-link-inner--text">How to Play</span>
                </a>
            </li>
        }

        if (Model.Collection.CallLink != null)
        {
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-secondary text-default" href="@Model.Collection.CallLink" target="_blank" style="@{ if (Model.Collection.BaseColor != null) { <text>background-color: @Model.Collection.LightColor !important; color: @Model.Collection.DarkestColor !important; border: 0;</text> } }">
                    <i class="fas fa-headset"></i>
                    <span class="nav-link-inner--text">Join Call</span>
                </a>
            </li>
        }

        if (Model.Collection.Private || Model.Private)
        {
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-dark text-danger" style="@{ if (Model.Collection.BaseColor != null) { <text>background-color: @Model.Collection.NearBlackColor !important; color: @Model.Collection.LightestColor !important; border: 0;</text> } }"
                   href="#" data-container="body" data-toggle="popover" data-placement="bottom"
                   title="This stream is private" data-content="Please do not share the link to it.">
                    <i class="fas fa-lock"></i>
                </a>
            </li>
        }
        else
        {
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-secondary text-default" style="@{ if (Model.Collection.BaseColor != null) { <text>background-color: @Model.Collection.LighterColor !important; color: @Model.Collection.DarkestColor !important; border: 0;</text> } }"
                   href="#" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true"
                   title="Share this stream!" data-content="<a href='@Url.ActionLink("ViewStream", "Player", new {url = Model.ID})'>@Url.ActionLink("ViewStream", "Player", new {url = Model.ID})</a>">
                    <i class="fad fa-share-alt"></i>
                </a>
            </li>
        }

        @if (User.Identity.IsAuthenticated)
        {
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-secondary text-default" style="@{ if (Model.Collection.BaseColor != null) { <text>background-color: @Model.Collection.LighterColor !important; color: @Model.Collection.DarkestColor !important; border: 0;</text> } }"
                   href="#" data-container="body" data-toggle="popover" data-placement="bottom" data-html="true"
                   data-content="<p class='text-center'>To start broadcasting, set up OBS with the following parameters.</p><div class='text-center'><strong class='d-block'>Ingest Server</strong> <span class='d-block'>@ViewData["IngestEndpoint"]</span></div><div class='text-center'><strong class='d-block'>Stream Key</strong> <span class='d-block'>@Model.StreamKey</span></div>">
                    <i class="fad fa-signal-stream"></i>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-btn nav-link nav-link-icon btn btn-secondary text-default" style="@{ if (Model.Collection.BaseColor != null) { <text>background-color: @Model.Collection.LighterColor !important; color: @Model.Collection.DarkestColor !important; border: 0;</text> } }"
                   asp-action="Edit" asp-controller="Streams" asp-route-url="@Model.CollectionURL" asp-route-id="@Model.ID">
                    <i class="fad fa-pencil"></i>
                </a>
            </li>
        }
    }
}

@if (Model.Collection.InstructionType == InstructionType.Jackbox)
{
    <partial name="Partials/Instructions/_Jackbox"/>
}